### ISSUE TITLE
enhancement: multiple panes

### ISSUE THREAD

**Issue by joshuajeschek** [composer404/tabby-workspace-manager#11]
Hi! I'd find it really helpful if we could not only create multiple tabs, put also multiple panes inside those tabs, and then run different commands inside each one of them.
The configuration could look like this:
```yaml
# Single pane (just like now, for backwards compatibility)
- title: ...
  profile: ...
  color: ...
  commands:
    - cd ...
    - ls ...

# Multiple panes
- title: ...
  profile: ...
  color: ...
  panes:
    - id: 1
      type: horizontal
      size: 0.5
      panes:
        - id: 2
          type: vertical
          size: 0.2
          commands:
            - cd ...
            - ls ...
        - id: 3
          type: vertical
          size: 0.8
          commands:
            - cd ...
            - ls ...
     - id: 4
       type: horizontal
       size: 0.5
       commands:
         - cd ...
         - ls ...
```

this is just a quick idea, for example the `type` property could be improved, maybe moved to the parents. I was thinking some kind of recursive setup would be fitting, and maybe we could also move the commands out of the panes property, and adress them through the IDs 🤔 a thing to keep in mind is that only `leaf panes`, so only the innermost panes can receive commands (the other ones are only containers)

and I also don't know how to implement this, but maybe I'll learn this and try this out on my own :)
