### ISSUE TITLE
Feature Request: Mulitple Windows with placement

### ISSUE THREAD

**Issue by Lockszmith-GH** [composer404/tabby-workspace-manager#9]
This is probably 2 separate features, but I only see them effective together.

I use a multi-monitor environment, where I have one windows with most of my work tabs, and another window on the side monitor for where I have a session open with `htop` to monitor the system.

A way to launch a complete tabby workspace (1x window in specific location with my work tabs - about 5 and 1x window on the other monitor for `htop`) would be absolutely awesome! Especially tied with #8

I'm thinking, the yaml structure would look like this:
```yaml
windows:
# absolute positioning - necessary to implement, but I would prefer relative positioning (see next)
# name: main-absolute
# screen: 1
# position:
#   x: 0
#   y: 720
#     height: 720
#     width: 1920
  name: main-relative
    screen: 1
    position:
      x: 5%
      y: 5%
      height: 90%
      width: 90%
  name: side-full
    screen: 2
    position:
      x: 0
      y: 0
      height: 100%
      width: 100%
tabs:
  - profile: 'ssh-main'
    window: main-relative
  - profile: 'ssh-monitor'
    window: side-full
```
